# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM

# Setup
title:               How To Know
tagline:             'unleash people and product'
description:         'How To Know is a about product management, leadership and software development. We aim to help you unleash your potential and make a difference in the world.'
url:                 'https://howtoknow.se/'
baseurl:             '/'
paginate:            5
permalink:           pretty
paginate_path:       "blog/page:num"
#banner:              banner.jpg

# About/contact
author:
  name:              Patrik Gustafsson
  url:               https://www.linkedin.com/in/paven/
  email:             info@howtoknow.se

# Custom vars
version:          0.0.2
google_analytics_id: #UA-XXXX-Y

github:
  repo:           https://github.com/howtoknowhub/howtoknow.se

plugins:
  - jekyll-paginate
  - jekyll-sitemap

first_page:
  url: 

